name: JupSheets
channels:
- anaconda-fusion
- defaults
dependencies:
- _nb_ext_conf=0.4.0=py27_1
- anaconda-client=1.6.11=py27_0
- appnope=0.1.0=py27hb466136_0
- asn1crypto=0.24.0=py27_0
- backports=1.0=py27hb4f9756_1
- backports.shutil_get_terminal_size=1.0.0=py27hc9115de_2
- backports_abc=0.5=py27h6972548_0
- bleach=2.1.2=py27_0
- ca-certificates=2017.08.26=ha1e5d58_0
- certifi=2018.1.18=py27_0
- cffi=1.11.4=py27h342bebf_0
- chardet=3.0.4=py27h2842e91_1
- clyent=1.2.2=py27hc0ae608_0
- configparser=3.5.0=py27hc7edf1b_0
- cryptography=2.1.4=py27hdbc5e8f_0
- dbus=1.12.2=h5243cc1_1
- decorator=4.2.1=py27_0
- entrypoints=0.2.3=py27hd680fb1_2
- enum34=1.1.6=py27hf475452_1
- expat=2.2.5=hb8e80ba_0
- functools32=3.2.3.2=py27h8ceab06_1
- gettext=0.19.8.1=h15daf44_3
- glib=2.53.6=h33f6a65_2
- html5lib=1.0.1=py27h5233db4_0
- icu=58.2=h4b95b61_1
- idna=2.6=py27hedea723_1
- intel-openmp=2018.0.0=h8158457_8
- ipaddress=1.0.19=py27_0
- ipykernel=4.8.2=py27_0
- ipython=5.4.1=py27_2
- ipython_genutils=0.2.0=py27h8b9a179_0
- ipywidgets=7.1.2=py27_0
- jinja2=2.10=py27h70b8dc5_0
- jpeg=9b=he5867d9_2
- jsonschema=2.6.0=py27hd9b497e_0
- jupyter=1.0.0=py27_4
- jupyter_client=5.2.2=py27_0
- jupyter_console=5.2.0=py27h9702a86_1
- jupyter_core=4.4.0=py27h5ea6ba4_0
- libcxx=4.0.1=h579ed51_0
- libcxxabi=4.0.1=hebd6815_0
- libedit=3.1=hb4e282d_0
- libffi=3.2.1=h475c297_4
- libgfortran=3.0.1=h93005f0_2
- libiconv=1.15=hdd342a3_7
- libpng=1.6.34=he12f830_0
- libsodium=1.0.15=hd9e47c5_0
- markupsafe=1.0=py27hd3c86fa_1
- mistune=0.8.3=py27_0
- mkl=2018.0.1=hfbd8650_4
- nb_anacondacloud=1.4.0=py27_0
- nb_conda=2.2.1=py27h9a0a3a7_0
- nb_conda_kernels=2.1.0=py27_0
- nbconvert=5.3.1=py27h6455e4c_0
- nbformat=4.4.0=py27hddc86d0_0
- nbpresent=3.0.2=py27h73ae17d_1
- ncurses=6.0=hd04f020_2
- notebook=5.4.0=py27_0
- numpy=1.14.1=py27h8a80b8c_1
- openssl=1.0.2n=hdbc3d79_0
- pandas=0.22.0=py27h0a44026_0
- pandoc=1.19.2.1=ha5e8f32_1
- pandocfilters=1.4.2=py27hed78c4e_1
- pathlib2=2.3.0=py27he09da1e_0
- pcre=8.41=hfb6ab37_1
- pexpect=4.4.0=py27_0
- pickleshare=0.7.4=py27h37e3d41_0
- pip=9.0.1=py27h1567d89_4
- prompt_toolkit=1.0.15=py27h4a7b9c2_0
- ptyprocess=0.5.2=py27h70f6364_0
- pycparser=2.18=py27h0d28d88_1
- pygments=2.2.0=py27h1a556bb_0
- pyopenssl=17.5.0=py27hfda213f_0
- pyqt=5.6.0=py27hf21fe59_6
- pysocks=1.6.7=py27h1cff6a6_1
- python=2.7.14=hde5916a_29
- python-dateutil=2.6.1=py27hd56c96b_1
- pytz=2018.3=py27_0
- pyyaml=3.12=py27ha7932d0_1
- pyzmq=16.0.3=py27h91ccc67_0
- qt=5.6.2=h9975529_14
- qtconsole=4.3.1=py27hdc90b4f_0
- readline=7.0=hc1231fa_4
- requests=2.18.4=py27h9b2b37c_1
- scandir=1.7=py27h1de35cc_0
- send2trash=1.5.0=py27_0
- setuptools=38.5.1=py27_0
- simplegeneric=0.8.1=py27_2
- singledispatch=3.4.0.3=py27he22c18d_0
- sip=4.18.1=py27h6300f65_2
- six=1.11.0=py27h7252ba3_1
- sqlite=3.22.0=h3efe00b_0
- ssl_match_hostname=3.5.0.1=py27h8780752_2
- terminado=0.8.1=py27_1
- testpath=0.3.1=py27h72d81a5_0
- tk=8.6.7=h35a86e2_3
- tornado=4.5.3=py27_0
- traitlets=4.3.2=py27hcf08151_0
- urllib3=1.22=py27hc3787e9_0
- wcwidth=0.1.7=py27h817c265_0
- webencodings=0.5.1=py27h19a9f58_1
- wheel=0.30.0=py27h677a027_1
- widgetsnbextension=3.1.4=py27_0
- yaml=0.1.7=hc338f04_2
- zeromq=4.2.2=ha360ad0_2
- zlib=1.2.11=hf3cbc9b_2
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - df2gspread==0.2.5
  - google-api-python-client==1.6.2
  - gspread==0.6.2
  - httplib2==0.10.3
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.2
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - nb-anacondacloud==1.4.0
  - nb-conda==2.2.1
  - nb-conda-kernels==2.1.0
  - oauth2client==4.1.2
  - prompt-toolkit==1.0.15
  - pyasn1==0.4.2
  - pyasn1-modules==0.2.1
  - pycrypto==2.6.1
  - rsa==3.4.2
  - uritemplate==3.0.0
prefix: /anaconda/envs/JupSheets

